version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-^-yp9i9n+tn0r(%)y!92c206-az0i^llom=#4j^2)-@az%0e0#
      - DJANGO_SETTINGS_MODULE=LastDjangoProject.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1
    restart: unless-stopped

# For future expansion, you can add more services like:
# 
# db:
#   image: postgres:13
#   volumes:
#     - postgres_data:/var/lib/postgresql/data/
#   environment:
#     - POSTGRES_PASSWORD=postgres
#     - POSTGRES_USER=postgres
#     - POSTGRES_DB=postgres
#   restart: unless-stopped
# 
# volumes:
#   postgres_data: