version: '3.8'

services:
  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-^-yp9i9n+tn0r(%)y!92c206-az0i^llom=#4j^2)-@az%0e0#
      - DJANGO_SETTINGS_MODULE=LastDjangoProject.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - KAVENEGAR_API_KEY=6B533653785957676E636938795A4A4F5945396A64304E553861736752743976352F464F7951725A666F6B3D
      - KAVENEGAR_SENDER=2000660110
      - PORT=8000
    restart: unless-stopped

volumes:
  static_volume:

# For future expansion with database