# Generated by Django 5.2.1 on 2025-05-19 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_category_subcategory_response_subcategoryresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dashboard.group'),
        ),
        migrations.AlterField(
            model_name='response',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dashboard.subcategory'),
        ),
    ]
