# Generated by Django 5.2.2 on 2025-06-09 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_checklistquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistquestion',
            name='active_system',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='exit', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistquestion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_questions', to='dashboard.group'),
        ),
    ]
