# Generated by Django 5.2.2 on 2025-06-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_checklistquestion_active_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistquestion',
            name='active_system',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5),
        ),
    ]
