# Generated by Django 5.2.2 on 2025-06-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_checklistquestion_active_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistquestion',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroup_checklist_questions', to='dashboard.group'),
        ),
    ]
