# Generated by Django 5.2.2 on 2025-06-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_checklistquestion_subgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistquestion',
            options={'permissions': [('manage_checklist_settings', 'Can manage checklist settings')]},
        ),
    ]
