# Generated by Django 5.2.2 on 2025-06-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_checklistquestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistquestion',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text Response'), ('FILE', 'File Upload')], default='TEXT', max_length=10),
        ),
        migrations.AddField(
            model_name='response',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='responses/'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
